### PR TITLE
Update to 16.40-348864

### PR DESCRIPTION
**Pull request by maiself**
This is based of off the patches from NixOS/nixpkgs.

I was able to get dkms building and OpenGL/CL working, but I haven't had time to sort out i386 or omx drivers. In addition there was quite a bit of change in how things were packaged between 16.30 and 16.40, and rather than rewrite a bunch of config files I just let things install to /opt. Maybe someone else can take this further.

Also thanks for the awesome work, this package as been a great help!

### CODE REVIEW

**Comment by parkerlreed** [comment]
Question: Why are we having to worry about the out of tree kernel module? I thought the whole point of AMDGPU-Pro was that it overlays with the OSS amdgpu driver. (I haven't been able to test as of recently since the AUR PKGBUILds aren't working at the moment)

**Comment by Kozzi11** [comment]
@parkerlreed because it is not true right now, there is lot of works whicj is still not part of mainline kernel tree. But yes one day it will be probably possible to use amdgpu pro with mainline amdgpu kernel module

**Comment by parkerlreed** [comment]
Ahh thanks. It worked for me previously so I didn't realize a lot had changed.

**Comment by corngood** [comment]
@parkerlreed  In my experience it does sort of work in that the user space detects the OSS kernel and works around some missing syscalls.  However, performance is probably impacted, and some things (like fences in vulkan) just fail silently, so I wouldn't recommend it.

**Comment by corngood** [comment]
16.60 is now merged

**Pull request closed without merging**
